package Vistas;

/*
 * @author Grupo 6
 * Gimenez Diego Ruben 
 * Carlos German Mecias Giacomelli Tomas
 * Migliozzi Badani Urbani Jose
 */
public class VistaEmpleados extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaAlumnos
     */
    public VistaEmpleados() {
        initComponents();
        setTitle("Alumnos");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlAlumno = new javax.swing.JLabel();
        jlDocumento = new javax.swing.JLabel();
        jlApellido = new javax.swing.JLabel();
        jlNombre = new javax.swing.JLabel();
        jlTelefono = new javax.swing.JLabel();
        jbtNuevo = new javax.swing.JButton();
        jbtEliminar = new javax.swing.JButton();
        jbtGuardar = new javax.swing.JButton();
        jbtSalir = new javax.swing.JButton();
        jtxDocumento = new javax.swing.JTextField();
        jtxtApellido = new javax.swing.JTextField();
        jtxtNombre = new javax.swing.JTextField();
        jdcFechadeNacimiento = new com.toedter.calendar.JDateChooser();
        jbtBuscar = new javax.swing.JButton();
        jlEstado1 = new javax.swing.JLabel();
        jlFechaDeNacimiento1 = new javax.swing.JLabel();
        jCB_PuestoParaTabla = new javax.swing.JComboBox<>();
        jlFechaDeNacimiento2 = new javax.swing.JLabel();
        jlMatricula = new javax.swing.JLabel();
        jtxTelefono = new javax.swing.JTextField();
        jlEspecialidad = new javax.swing.JLabel();
        jtxMatricula = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbEmpleados = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        cmbEspecialidadBuscar = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jtxtBuscar = new javax.swing.JTextField();
        jbtAltaBaja = new javax.swing.JButton();
        jCheckBoxEstado = new javax.swing.JCheckBox();
        rbtnActivo1 = new javax.swing.JRadioButton();
        rbtnInactivo1 = new javax.swing.JRadioButton();
        jComboBoxEspecialidad = new javax.swing.JComboBox<>();
        jComboBoxPuesto = new javax.swing.JComboBox<>();
        jlFechaDeNacimiento3 = new javax.swing.JLabel();

        setResizable(false);
        setPreferredSize(new java.awt.Dimension(1130, 663));

        jlAlumno.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jlAlumno.setForeground(new java.awt.Color(0, 102, 255));
        jlAlumno.setText("Empleados");

        jlDocumento.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlDocumento.setText("D.N.I:");

        jlApellido.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jlApellido.setText("Apellido:");
        jlApellido.setToolTipText("");

        jlNombre.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jlNombre.setText("Nombre:");

        jlTelefono.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jlTelefono.setText("Teléfono:");
        jlTelefono.setToolTipText("");

        jbtNuevo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbtNuevo.setForeground(new java.awt.Color(51, 255, 0));
        jbtNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon_nuevo.png"))); // NOI18N
        jbtNuevo.setText("Nuevo");
        jbtNuevo.setIconTextGap(2);
        jbtNuevo.setMargin(new java.awt.Insets(2, 6, 2, 6));

        jbtEliminar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jbtEliminar.setForeground(new java.awt.Color(255, 0, 51));
        jbtEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon_eliminar.png"))); // NOI18N
        jbtEliminar.setText("Eliminar");
        jbtEliminar.setAlignmentY(0.0F);
        jbtEliminar.setIconTextGap(2);
        jbtEliminar.setMargin(new java.awt.Insets(6, 6, 6, 6));

        jbtGuardar.setBackground(new java.awt.Color(204, 255, 204));
        jbtGuardar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbtGuardar.setForeground(new java.awt.Color(0, 204, 102));
        jbtGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon_guardar.png"))); // NOI18N
        jbtGuardar.setText("Guardar");
        jbtGuardar.setIconTextGap(2);
        jbtGuardar.setMargin(new java.awt.Insets(2, 6, 2, 6));

        jbtSalir.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jbtSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon_salir.png"))); // NOI18N
        jbtSalir.setText("Salir");
        jbtSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSalirActionPerformed(evt);
            }
        });

        jtxDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxDocumentoActionPerformed(evt);
            }
        });

        jbtBuscar.setBackground(new java.awt.Color(204, 204, 255));
        jbtBuscar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbtBuscar.setForeground(new java.awt.Color(51, 0, 255));
        jbtBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon_buscar.png"))); // NOI18N
        jbtBuscar.setText("Buscar");
        jbtBuscar.setMargin(new java.awt.Insets(2, 6, 3, 6));
        jbtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtBuscarActionPerformed(evt);
            }
        });

        jlEstado1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jlEstado1.setText("Estado");

        jlFechaDeNacimiento1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jlFechaDeNacimiento1.setText("Fecha Nac.:");
        jlFechaDeNacimiento1.setToolTipText("");

        jCB_PuestoParaTabla.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masajista", "Estilista", "Estetisista", "Recepcionista", "Técnico", "Administrativo", "Jefe" }));

        jlFechaDeNacimiento2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jlFechaDeNacimiento2.setText("Puesto:");
        jlFechaDeNacimiento2.setToolTipText("");

        jlMatricula.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jlMatricula.setText("Matrícula:");
        jlMatricula.setToolTipText("");

        jlEspecialidad.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jlEspecialidad.setText("Especialidad:");
        jlEspecialidad.setToolTipText("");

        jtxMatricula.setMinimumSize(null);
        jtxMatricula.setPreferredSize(null);

        tbEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbEmpleados.setMaximumSize(new java.awt.Dimension(2147483647, 900));
        tbEmpleados.setPreferredSize(null);
        jScrollPane1.setViewportView(tbEmpleados);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Listar por Especialidad");

        cmbEspecialidadBuscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbEspecialidadBuscar.setSelectedIndex(-1);
        cmbEspecialidadBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEspecialidadBuscarActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Matricula");

        jbtAltaBaja.setBackground(new java.awt.Color(255, 204, 255));
        jbtAltaBaja.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jbtAltaBaja.setForeground(new java.awt.Color(255, 0, 51));
        jbtAltaBaja.setText("Dar de Baja");
        jbtAltaBaja.setIconTextGap(2);
        jbtAltaBaja.setMargin(new java.awt.Insets(2, 6, 2, 6));

        jCheckBoxEstado.setForeground(new java.awt.Color(51, 255, 51));
        jCheckBoxEstado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jCheckBoxEstado.setPreferredSize(new java.awt.Dimension(20, 20));

        rbtnActivo1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        rbtnActivo1.setForeground(new java.awt.Color(0, 204, 0));
        rbtnActivo1.setSelected(true);
        rbtnActivo1.setText("Activos");

        rbtnInactivo1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        rbtnInactivo1.setForeground(new java.awt.Color(255, 51, 51));
        rbtnInactivo1.setText("Inactivos");

        jComboBoxEspecialidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Facial", "Corporal", "Relajación", "Terapéutico" }));

        jComboBoxPuesto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masajista", "Estetisista", "Estilista", "Cosmetologa", "Recepcionista", "Técnico", "Chofer", "Maestranza", "Administrativo", "RRHH", "Jefe" }));

        jlFechaDeNacimiento3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jlFechaDeNacimiento3.setText("Listar por Puesto:");
        jlFechaDeNacimiento3.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jlMatricula)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jlEspecialidad)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jComboBoxEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlFechaDeNacimiento1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jdcFechadeNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                                        .addComponent(jlEstado1)
                                        .addGap(6, 6, 6))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jlDocumento)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jtxDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbtBuscar)
                                        .addGap(4, 4, 4))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jlApellido)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jtxtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlNombre)
                                        .addGap(12, 12, 12)
                                        .addComponent(jtxtNombre))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jlFechaDeNacimiento2)
                                            .addComponent(jlTelefono))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jtxTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jCheckBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(22, 22, 22))
                                            .addComponent(jComboBoxPuesto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(jlAlumno))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jbtEliminar))
                            .addComponent(jbtGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbEspecialidadBuscar, 0, 215, Short.MAX_VALUE)
                            .addComponent(jtxtBuscar))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(rbtnActivo1)
                                .addGap(18, 18, 18)
                                .addComponent(rbtnInactivo1)
                                .addGap(18, 18, 18)
                                .addComponent(jbtAltaBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jlFechaDeNacimiento3)
                                .addGap(18, 18, 18)
                                .addComponent(jCB_PuestoParaTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtSalir))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 816, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jlAlumno)
                        .addGap(13, 13, 13))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cmbEspecialidadBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCB_PuestoParaTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlFechaDeNacimiento3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(rbtnInactivo1)
                                .addComponent(rbtnActivo1)
                                .addComponent(jbtAltaBaja))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jtxtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbtSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jbtBuscar)
                                .addGap(10, 10, 10))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtxDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlDocumento))
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlApellido)
                            .addComponent(jtxtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlNombre)
                            .addComponent(jtxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlFechaDeNacimiento1)
                            .addComponent(jdcFechadeNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlEstado1))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlTelefono)
                            .addComponent(jtxTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlFechaDeNacimiento2)
                            .addComponent(jComboBoxPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlEspecialidad)
                            .addComponent(jComboBoxEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlMatricula)
                            .addComponent(jtxMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtSalirActionPerformed

    private void jtxDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxDocumentoActionPerformed

    private void jbtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtBuscarActionPerformed

    private void cmbEspecialidadBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEspecialidadBuscarActionPerformed
        String especialidad = (String) cmbEspecialidadBuscar.getSelectedItem();

        /*listarPorEspecialidad(especialidad);*/
    }//GEN-LAST:event_cmbEspecialidadBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> cmbEspecialidadBuscar;
    public javax.swing.JComboBox<String> jCB_PuestoParaTabla;
    public javax.swing.JCheckBox jCheckBoxEstado;
    public javax.swing.JComboBox<String> jComboBoxEspecialidad;
    public javax.swing.JComboBox<String> jComboBoxPuesto;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton jbtAltaBaja;
    public javax.swing.JButton jbtBuscar;
    public javax.swing.JButton jbtEliminar;
    public javax.swing.JButton jbtGuardar;
    public javax.swing.JButton jbtNuevo;
    public javax.swing.JButton jbtSalir;
    public com.toedter.calendar.JDateChooser jdcFechadeNacimiento;
    private javax.swing.JLabel jlAlumno;
    private javax.swing.JLabel jlApellido;
    private javax.swing.JLabel jlDocumento;
    public javax.swing.JLabel jlEspecialidad;
    private javax.swing.JLabel jlEstado1;
    private javax.swing.JLabel jlFechaDeNacimiento1;
    private javax.swing.JLabel jlFechaDeNacimiento2;
    private javax.swing.JLabel jlFechaDeNacimiento3;
    private javax.swing.JLabel jlMatricula;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JLabel jlTelefono;
    public javax.swing.JTextField jtxDocumento;
    public javax.swing.JTextField jtxMatricula;
    public javax.swing.JTextField jtxTelefono;
    public javax.swing.JTextField jtxtApellido;
    public javax.swing.JTextField jtxtBuscar;
    public javax.swing.JTextField jtxtNombre;
    public javax.swing.JRadioButton rbtnActivo1;
    public javax.swing.JRadioButton rbtnInactivo1;
    public javax.swing.JTable tbEmpleados;
    // End of variables declaration//GEN-END:variables
}
