package Vistas;

import java.beans.PropertyVetoException;

/*  @author Grupo 6 
    Gimenez Diego Ruben
    Carlos German Mecias Giacomelli
    Tomas Migliozzi Badani
    Urbani Jose
 */
public class VistaSesiones extends javax.swing.JInternalFrame {

    /**
     * Creates new form Sesiones
     */
    public VistaSesiones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSesiones = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jDC_Fecha = new com.toedter.calendar.JDateChooser();
        jLabelFecha = new javax.swing.JLabel();
        jLabelHoraIni = new javax.swing.JLabel();
        jLabel_TipoTratamiento = new javax.swing.JLabel();
        jCmb_TipoTratamiento = new javax.swing.JComboBox<>();
        jCmb_HoraInicio = new javax.swing.JComboBox<>();
        jLabel_Especialidad = new javax.swing.JLabel();
        jCmb_Especialidad = new javax.swing.JComboBox<>();
        jCmb_Tratamiento = new javax.swing.JComboBox<>();
        jLabel_Tratamiento = new javax.swing.JLabel();
        jLabel_Profesional = new javax.swing.JLabel();
        jCmb_Profesional = new javax.swing.JComboBox<>();
        jLabel_Instalacion = new javax.swing.JLabel();
        jCmb_Instalacion = new javax.swing.JComboBox<>();
        jLabel_Consultorio = new javax.swing.JLabel();
        jCmb_Consultorio = new javax.swing.JComboBox<>();
        jLabel_MontoSes = new javax.swing.JLabel();
        jTextField_MontoSesion = new javax.swing.JTextField();
        jButton_LimpiarCampos = new javax.swing.JButton();
        jButton_Agregar = new javax.swing.JButton();
        jButton_Salir = new javax.swing.JButton();
        jLabel_NumPack = new javax.swing.JLabel();
        jTextField_NumPack = new javax.swing.JTextField();
        jButton_BuscarPack = new javax.swing.JButton();
        jButton_Modificar_Guardar = new javax.swing.JButton();
        jButton_Anular_Sesión = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbSesiones = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea_Notas = new javax.swing.JTextArea();
        jLabel_Notas = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        jCmb_HoraFin = new javax.swing.JComboBox<>();
        jLabelHoraF = new javax.swing.JLabel();
        jRadioButtonTodasSes = new javax.swing.JRadioButton();
        jRadioButtonSesInactivas = new javax.swing.JRadioButton();
        jRadioButtonSesActivas = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelSesiones.setBackground(new java.awt.Color(153, 0, 153));
        jPanelSesiones.setPreferredSize(new java.awt.Dimension(1081, 615));
        jPanelSesiones.setVerifyInputWhenFocusTarget(false);

        jLabelTitulo.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 204, 0));
        jLabelTitulo.setText("Gestion de sesiones");

        jLabelFecha.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelFecha.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFecha.setText("Fecha");

        jLabelHoraIni.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelHoraIni.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHoraIni.setText("Inicio");

        jLabel_TipoTratamiento.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel_TipoTratamiento.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_TipoTratamiento.setText("Tipo Tratam.");

        jCmb_TipoTratamiento.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jCmb_TipoTratamiento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Facial", "Corporal", "Relajacion", "Estetico" }));
        jCmb_TipoTratamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmb_TipoTratamientoActionPerformed(evt);
            }
        });

        jCmb_HoraInicio.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jCmb_HoraInicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "08:00", "08:30", "09:00", "09:30", "10:00", "10:30", "11:00", "11:30", "12:00" }));

        jLabel_Especialidad.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel_Especialidad.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Especialidad.setText("Especialidad");

        jCmb_Especialidad.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jCmb_Tratamiento.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jLabel_Tratamiento.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel_Tratamiento.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Tratamiento.setText("Tratamiento");

        jLabel_Profesional.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel_Profesional.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Profesional.setText("Profesional");

        jCmb_Profesional.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jLabel_Instalacion.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel_Instalacion.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Instalacion.setText("Instalación");

        jCmb_Instalacion.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jLabel_Consultorio.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel_Consultorio.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Consultorio.setText("Consultorio");

        jCmb_Consultorio.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jLabel_MontoSes.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel_MontoSes.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_MontoSes.setText("Monto Sesion");

        jTextField_MontoSesion.setEditable(false);

        jButton_LimpiarCampos.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton_LimpiarCampos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon_limpiar.png"))); // NOI18N
        jButton_LimpiarCampos.setText("Limpiar");
        jButton_LimpiarCampos.setMargin(new java.awt.Insets(2, 5, 3, 5));

        jButton_Agregar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton_Agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon_agregar.png"))); // NOI18N
        jButton_Agregar.setText("Agregar");
        jButton_Agregar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton_Agregar.setMargin(new java.awt.Insets(2, 5, 3, 5));

        jButton_Salir.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton_Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon_buscar.png"))); // NOI18N
        jButton_Salir.setText("Salir");
        jButton_Salir.setMargin(new java.awt.Insets(2, 5, 3, 5));

        jLabel_NumPack.setBackground(new java.awt.Color(0, 0, 255));
        jLabel_NumPack.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel_NumPack.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_NumPack.setText("N° Pack (Turno)");

        jTextField_NumPack.setBackground(new java.awt.Color(255, 153, 255));
        jTextField_NumPack.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextField_NumPack.setSelectionColor(new java.awt.Color(0, 255, 153));

        jButton_BuscarPack.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton_BuscarPack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon_buscar.png"))); // NOI18N
        jButton_BuscarPack.setText("Buscar");
        jButton_BuscarPack.setMargin(new java.awt.Insets(2, 5, 3, 5));

        jButton_Modificar_Guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon_guardar.png"))); // NOI18N
        jButton_Modificar_Guardar.setText("Modificar /Guardar");
        jButton_Modificar_Guardar.setMargin(new java.awt.Insets(2, 5, 3, 5));

        jButton_Anular_Sesión.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon_eliminar.png"))); // NOI18N
        jButton_Anular_Sesión.setText("Anular Sesion");
        jButton_Anular_Sesión.setMargin(new java.awt.Insets(2, 5, 3, 5));

        tbSesiones.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        tbSesiones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Estado", "Fecha / Hora", "Masajista", "Tratamiento", "Monto", "Notas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbSesiones.setMinimumSize(new java.awt.Dimension(60, 90));
        tbSesiones.setShowGrid(true);
        jScrollPane1.setViewportView(tbSesiones);
        if (tbSesiones.getColumnModel().getColumnCount() > 0) {
            tbSesiones.getColumnModel().getColumn(0).setPreferredWidth(10);
            tbSesiones.getColumnModel().getColumn(1).setPreferredWidth(20);
            tbSesiones.getColumnModel().getColumn(2).setPreferredWidth(30);
            tbSesiones.getColumnModel().getColumn(3).setResizable(false);
            tbSesiones.getColumnModel().getColumn(3).setPreferredWidth(10);
            tbSesiones.getColumnModel().getColumn(4).setPreferredWidth(30);
            tbSesiones.getColumnModel().getColumn(5).setPreferredWidth(10);
            tbSesiones.getColumnModel().getColumn(6).setPreferredWidth(30);
        }

        jTextArea_Notas.setColumns(20);
        jTextArea_Notas.setRows(5);
        jScrollPane2.setViewportView(jTextArea_Notas);

        jLabel_Notas.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel_Notas.setForeground(new java.awt.Color(255, 204, 51));
        jLabel_Notas.setText("Notas / Comentarios");

        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon_update.png"))); // NOI18N
        btnActualizar.setText("Actualizar / Refrescar Datos");

        jCmb_HoraFin.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jCmb_HoraFin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "08:00", "08:30", "09:00", "09:30", "10:00", "10:30", "11:00", "11:30", "12:00" }));

        jLabelHoraF.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelHoraF.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHoraF.setText("Fin");

        jRadioButtonTodasSes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButtonTodasSes.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonTodasSes.setText("Todas");

        jRadioButtonSesInactivas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButtonSesInactivas.setForeground(new java.awt.Color(255, 0, 102));
        jRadioButtonSesInactivas.setText("Inactivas");

        jRadioButtonSesActivas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButtonSesActivas.setForeground(new java.awt.Color(51, 255, 51));
        jRadioButtonSesActivas.setText("Activas");

        javax.swing.GroupLayout jPanelSesionesLayout = new javax.swing.GroupLayout(jPanelSesiones);
        jPanelSesiones.setLayout(jPanelSesionesLayout);
        jPanelSesionesLayout.setHorizontalGroup(
            jPanelSesionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSesionesLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabelTitulo)
                .addGroup(jPanelSesionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSesionesLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jRadioButtonTodasSes)
                        .addGap(36, 36, 36)
                        .addComponent(jRadioButtonSesActivas)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonSesInactivas)
                        .addGap(133, 133, 133)
                        .addComponent(btnActualizar))
                    .addGroup(jPanelSesionesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Modificar_Guardar)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_LimpiarCampos)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Anular_Sesión)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addComponent(jButton_Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(62, Short.MAX_VALUE))))
            .addGroup(jPanelSesionesLayout.createSequentialGroup()
                .addGroup(jPanelSesionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSesionesLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanelSesionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelSesionesLayout.createSequentialGroup()
                                .addGroup(jPanelSesionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelSesionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel_Tratamiento)
                                        .addComponent(jLabel_MontoSes)
                                        .addComponent(jLabel_Consultorio)
                                        .addComponent(jLabel_Instalacion)
                                        .addComponent(jLabel_Profesional)
                                        .addComponent(jLabel_Especialidad)
                                        .addComponent(jLabel_NumPack)
                                        .addComponent(jLabelHoraIni)
                                        .addComponent(jLabel_TipoTratamiento))
                                    .addComponent(jLabelFecha))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelSesionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelSesionesLayout.createSequentialGroup()
                                        .addGroup(jPanelSesionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jDC_Fecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jTextField_NumPack, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton_BuscarPack))
                                    .addGroup(jPanelSesionesLayout.createSequentialGroup()
                                        .addComponent(jCmb_HoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabelHoraF)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCmb_HoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jCmb_Profesional, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCmb_Tratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCmb_Especialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCmb_TipoTratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanelSesionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jCmb_Consultorio, javax.swing.GroupLayout.Alignment.LEADING, 0, 187, Short.MAX_VALUE)
                                        .addComponent(jCmb_Instalacion, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(jPanelSesionesLayout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(jTextField_MontoSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jButton_Agregar))))
                    .addGroup(jPanelSesionesLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanelSesionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_Notas))))
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanelSesionesLayout.setVerticalGroup(
            jPanelSesionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSesionesLayout.createSequentialGroup()
                .addGroup(jPanelSesionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTitulo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSesionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jRadioButtonSesActivas, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jRadioButtonSesInactivas))
                    .addComponent(btnActualizar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadioButtonTodasSes, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelSesionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanelSesionesLayout.createSequentialGroup()
                        .addGroup(jPanelSesionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanelSesionesLayout.createSequentialGroup()
                                .addGroup(jPanelSesionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField_NumPack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_NumPack))
                                .addGap(15, 15, 15)
                                .addGroup(jPanelSesionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelFecha)
                                    .addComponent(jDC_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButton_BuscarPack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanelSesionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelHoraIni)
                            .addComponent(jCmb_HoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCmb_HoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelHoraF))
                        .addGap(15, 15, 15)
                        .addGroup(jPanelSesionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_TipoTratamiento)
                            .addComponent(jCmb_TipoTratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanelSesionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Especialidad)
                            .addComponent(jCmb_Especialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanelSesionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCmb_Tratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_Tratamiento))
                        .addGap(15, 15, 15)
                        .addGroup(jPanelSesionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCmb_Profesional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_Profesional))
                        .addGap(15, 15, 15)
                        .addGroup(jPanelSesionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCmb_Instalacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_Instalacion))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelSesionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCmb_Consultorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_Consultorio))
                        .addGap(15, 15, 15)
                        .addGroup(jPanelSesionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelSesionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel_MontoSes)
                                .addComponent(jTextField_MontoSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton_Agregar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_Notas)
                        .addGap(4, 4, 4))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanelSesionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSesionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton_LimpiarCampos)
                        .addComponent(jButton_Anular_Sesión)
                        .addComponent(jButton_Salir)
                        .addComponent(jButton_Modificar_Guardar))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelSesiones, javax.swing.GroupLayout.DEFAULT_SIZE, 1132, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelSesiones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCmb_TipoTratamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmb_TipoTratamientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCmb_TipoTratamientoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaSesiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaSesiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaSesiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaSesiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
 /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaSesiones().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnActualizar;
    public javax.swing.JButton jButton_Agregar;
    public javax.swing.JButton jButton_Anular_Sesión;
    public javax.swing.JButton jButton_BuscarPack;
    public javax.swing.JButton jButton_LimpiarCampos;
    public javax.swing.JButton jButton_Modificar_Guardar;
    public javax.swing.JButton jButton_Salir;
    public javax.swing.JComboBox<String> jCmb_Consultorio;
    public javax.swing.JComboBox<String> jCmb_Especialidad;
    public javax.swing.JComboBox<String> jCmb_HoraFin;
    public javax.swing.JComboBox<String> jCmb_HoraInicio;
    public javax.swing.JComboBox<String> jCmb_Instalacion;
    public javax.swing.JComboBox<String> jCmb_Profesional;
    public javax.swing.JComboBox<String> jCmb_TipoTratamiento;
    public javax.swing.JComboBox<String> jCmb_Tratamiento;
    public com.toedter.calendar.JDateChooser jDC_Fecha;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelHoraF;
    private javax.swing.JLabel jLabelHoraIni;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabel_Consultorio;
    private javax.swing.JLabel jLabel_Especialidad;
    private javax.swing.JLabel jLabel_Instalacion;
    private javax.swing.JLabel jLabel_MontoSes;
    private javax.swing.JLabel jLabel_Notas;
    private javax.swing.JLabel jLabel_NumPack;
    private javax.swing.JLabel jLabel_Profesional;
    private javax.swing.JLabel jLabel_TipoTratamiento;
    private javax.swing.JLabel jLabel_Tratamiento;
    public javax.swing.JPanel jPanelSesiones;
    public javax.swing.JRadioButton jRadioButtonSesActivas;
    public javax.swing.JRadioButton jRadioButtonSesInactivas;
    public javax.swing.JRadioButton jRadioButtonTodasSes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTextArea jTextArea_Notas;
    public javax.swing.JTextField jTextField_MontoSesion;
    public javax.swing.JTextField jTextField_NumPack;
    public javax.swing.JTable tbSesiones;
    // End of variables declaration//GEN-END:variables
}
