
package Vistas;

/*  @author Grupo 6 
    Gimenez Diego Ruben
    Carlos German Mecias Giacomelli
    Tomas Migliozzi Badani
    Urbani Jose
 */

public class VistaSesiones extends javax.swing.JInternalFrame {

    /**
     * Creates new form Sesiones
     */
    public VistaSesiones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSesiones = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jDC_Fecha = new com.toedter.calendar.JDateChooser();
        jLabelFecha = new javax.swing.JLabel();
        jLabelHora = new javax.swing.JLabel();
        jLabel_TipoTratamiento = new javax.swing.JLabel();
        jCmb_TipoTratamiento = new javax.swing.JComboBox<>();
        jCmb_Hora = new javax.swing.JComboBox<>();
        jLabel_Especialidad = new javax.swing.JLabel();
        jCmb_Especialidad = new javax.swing.JComboBox<>();
        jCmb_Tratamiento = new javax.swing.JComboBox<>();
        jLabel_Tratamiento = new javax.swing.JLabel();
        jLabel_Profesional = new javax.swing.JLabel();
        jCmb_Profesional = new javax.swing.JComboBox<>();
        jLabel_Instalacion = new javax.swing.JLabel();
        jCmb_Instalacion = new javax.swing.JComboBox<>();
        jLabel_Consultorio = new javax.swing.JLabel();
        jCmb_Consultorio = new javax.swing.JComboBox<>();
        jLabel_MontoSes = new javax.swing.JLabel();
        jTextField_MontoSesion = new javax.swing.JTextField();
        jButton_LimpiarCampos = new javax.swing.JButton();
        jButton_Agregar = new javax.swing.JButton();
        jButton_Salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelSesiones.setBackground(new java.awt.Color(0, 204, 153));

        jLabelTitulo.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(0, 102, 102));
        jLabelTitulo.setText("       Gestion de sesiones");

        jLabelFecha.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabelFecha.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFecha.setText("Fecha");

        jLabelHora.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabelHora.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHora.setText("Hora");

        jLabel_TipoTratamiento.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel_TipoTratamiento.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_TipoTratamiento.setText("Tipo Tratam.");

        jCmb_TipoTratamiento.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jCmb_TipoTratamiento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Facial", "Corporal", "Relajacion", "Estetico" }));
        jCmb_TipoTratamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmb_TipoTratamientoActionPerformed(evt);
            }
        });

        jCmb_Hora.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jCmb_Hora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "08:00", "08:30", "09:00", "09:30", "10:00", "10:30", "11:00", "11:30", "12:00" }));

        jLabel_Especialidad.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel_Especialidad.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Especialidad.setText("Especialidad");

        jCmb_Especialidad.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jCmb_Tratamiento.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jLabel_Tratamiento.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel_Tratamiento.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Tratamiento.setText("Tratamiento");

        jLabel_Profesional.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel_Profesional.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Profesional.setText("Profesional");

        jCmb_Profesional.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jLabel_Instalacion.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel_Instalacion.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Instalacion.setText("Instalación");

        jCmb_Instalacion.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jLabel_Consultorio.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel_Consultorio.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Consultorio.setText("Consultorio");

        jCmb_Consultorio.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jLabel_MontoSes.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel_MontoSes.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_MontoSes.setText("Monto");

        jButton_LimpiarCampos.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton_LimpiarCampos.setText("Limpiar");

        jButton_Agregar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton_Agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon_inscribir.png"))); // NOI18N
        jButton_Agregar.setText("Agregar");

        jButton_Salir.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton_Salir.setText("Salir");

        javax.swing.GroupLayout jPanelSesionesLayout = new javax.swing.GroupLayout(jPanelSesiones);
        jPanelSesiones.setLayout(jPanelSesionesLayout);
        jPanelSesionesLayout.setHorizontalGroup(
            jPanelSesionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSesionesLayout.createSequentialGroup()
                .addGroup(jPanelSesionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelSesionesLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanelSesionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelSesionesLayout.createSequentialGroup()
                                .addGroup(jPanelSesionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel_Tratamiento)
                                    .addComponent(jLabel_MontoSes)
                                    .addComponent(jLabel_Consultorio)
                                    .addComponent(jButton_LimpiarCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_Instalacion)
                                    .addComponent(jLabel_Profesional))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelSesionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton_Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanelSesionesLayout.createSequentialGroup()
                                        .addComponent(jTextField_MontoSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton_Agregar))
                                    .addComponent(jCmb_Consultorio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCmb_Instalacion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCmb_Profesional, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCmb_Tratamiento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabelTitulo)))
                    .addGroup(jPanelSesionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanelSesionesLayout.createSequentialGroup()
                            .addGap(91, 91, 91)
                            .addGroup(jPanelSesionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabelHora)
                                .addComponent(jLabelFecha))
                            .addGap(18, 18, 18)
                            .addGroup(jPanelSesionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jCmb_Hora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jDC_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(jPanelSesionesLayout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addGroup(jPanelSesionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel_Especialidad)
                                .addComponent(jLabel_TipoTratamiento))
                            .addGap(18, 18, 18)
                            .addGroup(jPanelSesionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jCmb_Especialidad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jCmb_TipoTratamiento, 0, 250, Short.MAX_VALUE)))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanelSesionesLayout.setVerticalGroup(
            jPanelSesionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSesionesLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabelTitulo)
                .addGap(37, 37, 37)
                .addGroup(jPanelSesionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDC_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFecha))
                .addGap(22, 22, 22)
                .addGroup(jPanelSesionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHora)
                    .addComponent(jCmb_Hora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanelSesionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_TipoTratamiento)
                    .addComponent(jCmb_TipoTratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanelSesionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Especialidad)
                    .addComponent(jCmb_Especialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanelSesionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCmb_Tratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Tratamiento))
                .addGap(20, 20, 20)
                .addGroup(jPanelSesionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCmb_Profesional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Profesional))
                .addGap(18, 18, 18)
                .addGroup(jPanelSesionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCmb_Instalacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Instalacion))
                .addGap(18, 18, 18)
                .addGroup(jPanelSesionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCmb_Consultorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Consultorio))
                .addGap(18, 18, 18)
                .addGroup(jPanelSesionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_MontoSes)
                    .addComponent(jButton_Agregar)
                    .addComponent(jTextField_MontoSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanelSesionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_LimpiarCampos, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(jButton_Salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jPanelSesiones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelSesiones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCmb_TipoTratamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmb_TipoTratamientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCmb_TipoTratamientoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaSesiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaSesiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaSesiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaSesiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaSesiones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton_Agregar;
    public javax.swing.JButton jButton_LimpiarCampos;
    public javax.swing.JButton jButton_Salir;
    public javax.swing.JComboBox<String> jCmb_Consultorio;
    public javax.swing.JComboBox<String> jCmb_Especialidad;
    public javax.swing.JComboBox<String> jCmb_Hora;
    public javax.swing.JComboBox<String> jCmb_Instalacion;
    public javax.swing.JComboBox<String> jCmb_Profesional;
    public javax.swing.JComboBox<String> jCmb_TipoTratamiento;
    public javax.swing.JComboBox<String> jCmb_Tratamiento;
    public com.toedter.calendar.JDateChooser jDC_Fecha;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelHora;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabel_Consultorio;
    private javax.swing.JLabel jLabel_Especialidad;
    private javax.swing.JLabel jLabel_Instalacion;
    private javax.swing.JLabel jLabel_MontoSes;
    private javax.swing.JLabel jLabel_Profesional;
    private javax.swing.JLabel jLabel_TipoTratamiento;
    private javax.swing.JLabel jLabel_Tratamiento;
    public javax.swing.JPanel jPanelSesiones;
    public javax.swing.JTextField jTextField_MontoSesion;
    // End of variables declaration//GEN-END:variables
}
