package Vistas;

import Modelos.Instalacion;
import Persistencias_Conexion.InstalacionData;
import java.util.List;
import javax.swing.table.DefaultTableModel;
/*  @author Grupo 6 
    Gimenez Diego Ruben
    Carlos German Mecias Giacomelli
    Tomas Migliozzi Badani
    Urbani Jose
 */
public class VistaInstalacion extends javax.swing.JInternalFrame {
    
    private DefaultTableModel modelo;
    private InstalacionData instalacionData= new InstalacionData();
    /**
     * Creates new form VistaInstalacion
     */
    public VistaInstalacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabelTituloInstalaciones = new javax.swing.JLabel();
        jlNombre = new javax.swing.JLabel();
        jlDetalle = new javax.swing.JLabel();
        jtNombre = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtDetalle = new javax.swing.JTextArea();
        jlPrecio = new javax.swing.JLabel();
        jtPrecio = new javax.swing.JTextField();
        jlEstado = new javax.swing.JLabel();
        jchbEstado = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbInstalaciones = new javax.swing.JTable();
        jbtNuevo = new javax.swing.JToggleButton();
        jbtGuardar = new javax.swing.JButton();
        jbtEliminar = new javax.swing.JButton();
        jbtSalir = new javax.swing.JToggleButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabelTituloInstalaciones.setBackground(new java.awt.Color(0, 0, 0));
        jLabelTituloInstalaciones.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabelTituloInstalaciones.setText("Instalaciones");

        jlNombre.setBackground(new java.awt.Color(0, 0, 0));
        jlNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlNombre.setText("Nombre");

        jlDetalle.setBackground(new java.awt.Color(0, 0, 0));
        jlDetalle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlDetalle.setText("Detalle de uso:");

        jtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNombreActionPerformed(evt);
            }
        });

        jtDetalle.setColumns(20);
        jtDetalle.setRows(5);
        jScrollPane2.setViewportView(jtDetalle);

        jlPrecio.setBackground(new java.awt.Color(0, 0, 0));
        jlPrecio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlPrecio.setText("Precio (30min)");

        jlEstado.setBackground(new java.awt.Color(0, 0, 0));
        jlEstado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlEstado.setText("Estado(Activa/Inactiva)");

        jchbEstado.setBackground(new java.awt.Color(153, 0, 153));

        jtbInstalaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Precio (30m)", "Detalle", "Estado"
            }
        ));
        jScrollPane1.setViewportView(jtbInstalaciones);

        jbtNuevo.setForeground(new java.awt.Color(0, 51, 255));
        jbtNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon_nuevo.png"))); // NOI18N
        jbtNuevo.setText("Nueva instalacion");
        jbtNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtNuevoActionPerformed(evt);
            }
        });

        jbtGuardar.setForeground(new java.awt.Color(0, 51, 255));
        jbtGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon_guardar.png"))); // NOI18N
        jbtGuardar.setText("Guardar");
        jbtGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtGuardarActionPerformed(evt);
            }
        });

        jbtEliminar.setForeground(new java.awt.Color(255, 0, 0));
        jbtEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon_eliminar.png"))); // NOI18N
        jbtEliminar.setText("Eliminar");

        jbtSalir.setForeground(new java.awt.Color(255, 0, 0));
        jbtSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon_salir.png"))); // NOI18N
        jbtSalir.setText("Salir");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jlDetalle)
                                .addComponent(jlEstado)
                                .addComponent(jchbEstado)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(109, 109, 109))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jlPrecio)
                                    .addGap(101, 101, 101))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jlNombre)
                                    .addGap(127, 127, 127))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jbtGuardar))
                            .addComponent(jLabelTituloInstalaciones))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtSalir))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(176, Short.MAX_VALUE)
                        .addComponent(jbtNuevo)
                        .addGap(149, 149, 149)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtEliminar)
                    .addComponent(jbtSalir))
                .addGap(27, 27, 27))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabelTituloInstalaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jbtNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlDetalle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlPrecio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlEstado)
                .addGap(18, 18, 18)
                .addComponent(jchbEstado)
                .addGap(18, 18, 18)
                .addComponent(jbtGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    private void jtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtNombreActionPerformed

    private void jbtGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtGuardarActionPerformed

    private void jbtNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtNuevoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabelTituloInstalaciones;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JButton jbtEliminar;
    public javax.swing.JButton jbtGuardar;
    public javax.swing.JToggleButton jbtNuevo;
    public javax.swing.JToggleButton jbtSalir;
    public javax.swing.JCheckBox jchbEstado;
    private javax.swing.JLabel jlDetalle;
    private javax.swing.JLabel jlEstado;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JLabel jlPrecio;
    public javax.swing.JTextArea jtDetalle;
    public javax.swing.JTextField jtNombre;
    public javax.swing.JTextField jtPrecio;
    public javax.swing.JTable jtbInstalaciones;
    // End of variables declaration//GEN-END:variables

  /*  public void limpiarCampos(){
        jtfCodInstalacion.setText("");
        jtNombre.setText("");
        jtDetalle.setText("");
        jtPrecio.setText("");
        jchbEstado.setSelected(true);
    }
    
    public void cargarFormDesdeInstalacion(Instalacion instalacion){
        jtfCodInstalacion.setText(String.valueOf(instalacion.getCodInstal()));
        jtNombre.setText(instalacion.getNombre());
        jtPrecio.setText(String.valueOf(instalacion.getPrecio()));
        jtDetalle.setText(instalacion.getDetalleUso());
        jchbEstado.setSelected(instalacion.isEstado());
    }
    
    private void armarCabeceraTabla(){
        modelo = new DefaultTableModel(){
            
            @Override
            public boolean isCellEditable(int fila, int columna){
                return false;
            }
        };
                
        String[] titulos={"ID","Nombre","Precio (30m)","Detalle","Estado"};
        modelo.setColumnIdentifiers(titulos);
        jtbInstalaciones.setModel(modelo);
    }
    
    public void cargarTablaInstalaciones(){
        borrarFilas();
        
        try {
            List<Instalacion> listaInstalaciones= instalacionData.listarTodasInstalacionesActivas();
            
            for(Instalacion i: listaInstalaciones){
                modelo.addRow(new Object[]{
                    i.getCodInstal(),
                    i.getNombre(),
                    String.format(".2f", i.getPrecio()),
                    i.getDetalleUso(),
                    i.isEstado() ?  "Activa" : "Inactiva"
                });
            }
        } catch (Exception e) {
            
        }
        
    }
    
    private void borrarFilas(){
        int a= modelo.getRowCount()- 1;
        for(int i= a; i>=0;i--){
            modelo.removeRow(i);
        }
    }*/
}
