package Vistas;

import java.awt.Image;
import java.net.URL;
import javax.swing.ImageIcon;

public class Vista_MenuSpa extends javax.swing.JFrame {

    /**
     * Creates new form vistaMenuSpa
     */
    public Vista_MenuSpa() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/Icons/IconVista.png")).getImage()); // logo de la esquina para la vista App_Menu
        setExtendedState(MAXIMIZED_BOTH); // inicia maximizado
        colocarIconos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanelFondo = new javax.swing.JPanel();
        JDesktopPFondo = new javax.swing.JDesktopPane();
        JPanelBotones = new javax.swing.JPanel();
        jButtonSalir = new javax.swing.JButton();
        jButtonBusquedas = new javax.swing.JButton();
        jButtonClientes = new javax.swing.JButton();
        jButtonEmpleados = new javax.swing.JButton();
        jButtonInstalaciones = new javax.swing.JButton();
        jButtonTratamientos = new javax.swing.JButton();
        jButtonConsultorios = new javax.swing.JButton();
        jButtonTienda = new javax.swing.JButton();
        jButtonTurnos = new javax.swing.JButton();
        jButtonSpace = new javax.swing.JButton();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuEmpleados = new javax.swing.JMenu();
        jMenuVerEmpleados = new javax.swing.JMenuItem();
        jMenuBusquedas = new javax.swing.JMenu();
        jMenuHistorialSes_Turnos = new javax.swing.JMenuItem();
        jMenuHistorialClientes = new javax.swing.JMenuItem();
        jMenuHistorialTratamientos = new javax.swing.JMenuItem();
        jMenuTienda = new javax.swing.JMenu();
        jMenuHistorialVentas = new javax.swing.JMenuItem();
        jMenuHistorialProductos = new javax.swing.JMenuItem();
        jMenuEspaciador = new javax.swing.JMenu();
        jmSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Spa Entre Dedos");

        JPanelFondo.setBackground(new java.awt.Color(0, 255, 255));
        JPanelFondo.setNextFocusableComponent(JDesktopPFondo);

        JDesktopPFondo.setBackground(new java.awt.Color(153, 102, 255));

        javax.swing.GroupLayout JDesktopPFondoLayout = new javax.swing.GroupLayout(JDesktopPFondo);
        JDesktopPFondo.setLayout(JDesktopPFondoLayout);
        JDesktopPFondoLayout.setHorizontalGroup(
            JDesktopPFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1189, Short.MAX_VALUE)
        );
        JDesktopPFondoLayout.setVerticalGroup(
            JDesktopPFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        JPanelBotones.setBackground(new java.awt.Color(204, 204, 204));

        jButtonSalir.setText("Salir");

        jButtonBusquedas.setText("Busquedas / Historial");
        jButtonBusquedas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jButtonClientes.setText("Clientes");
        jButtonClientes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jButtonEmpleados.setText("Empleados");
        jButtonEmpleados.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jButtonInstalaciones.setText("Instalaciones");
        jButtonInstalaciones.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jButtonTratamientos.setText("Tratamientos");
        jButtonTratamientos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jButtonConsultorios.setText("Consultorios");
        jButtonConsultorios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jButtonTienda.setText("Tienda");
        jButtonTienda.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jButtonTurnos.setText("TURNOS");
        jButtonTurnos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jButtonSpace.setBorderPainted(false);
        jButtonSpace.setEnabled(false);
        jButtonSpace.setFocusPainted(false);
        jButtonSpace.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout JPanelBotonesLayout = new javax.swing.GroupLayout(JPanelBotones);
        JPanelBotones.setLayout(JPanelBotonesLayout);
        JPanelBotonesLayout.setHorizontalGroup(
            JPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelBotonesLayout.createSequentialGroup()
                .addGroup(JPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonSpace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonTienda, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(JPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButtonConsultorios, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonInstalaciones, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonTratamientos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonEmpleados, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonClientes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonBusquedas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                        .addComponent(jButtonTurnos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        JPanelBotonesLayout.setVerticalGroup(
            JPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelBotonesLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jButtonTurnos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButtonBusquedas, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButtonClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButtonEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButtonTratamientos, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButtonInstalaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButtonConsultorios, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButtonTienda, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButtonSpace, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButtonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JPanelFondoLayout = new javax.swing.GroupLayout(JPanelFondo);
        JPanelFondo.setLayout(JPanelFondoLayout);
        JPanelFondoLayout.setHorizontalGroup(
            JPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelFondoLayout.createSequentialGroup()
                .addComponent(JPanelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(JDesktopPFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        JPanelFondoLayout.setVerticalGroup(
            JPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JDesktopPFondo)
        );

        jMenuEmpleados.setText("Empleados");

        jMenuVerEmpleados.setText("Ver / Cargar Empleados");
        jMenuEmpleados.add(jMenuVerEmpleados);

        jMenuBar.add(jMenuEmpleados);

        jMenuBusquedas.setText("Busquedas");

        jMenuHistorialSes_Turnos.setText("Historial de Sesiones/Turnos");
        jMenuBusquedas.add(jMenuHistorialSes_Turnos);

        jMenuHistorialClientes.setText("Historial de Clientes");
        jMenuBusquedas.add(jMenuHistorialClientes);

        jMenuHistorialTratamientos.setText("Historial de Tratamientos");
        jMenuBusquedas.add(jMenuHistorialTratamientos);

        jMenuBar.add(jMenuBusquedas);

        jMenuTienda.setText("Tienda");

        jMenuHistorialVentas.setText("Historial de Ventas");
        jMenuTienda.add(jMenuHistorialVentas);

        jMenuHistorialProductos.setText("Historial de Productos");
        jMenuTienda.add(jMenuHistorialProductos);

        jMenuBar.add(jMenuTienda);

        jMenuEspaciador.setText("                      ");
        jMenuEspaciador.setContentAreaFilled(false);
        jMenuEspaciador.setEnabled(false);
        jMenuBar.add(jMenuEspaciador);

        jmSalir.setText("Salir");
        jMenuBar.add(jmSalir);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JPanelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista_MenuSpa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista_MenuSpa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista_MenuSpa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista_MenuSpa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>


          /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista_MenuSpa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JDesktopPane JDesktopPFondo;
    public javax.swing.JPanel JPanelBotones;
    public javax.swing.JPanel JPanelFondo;
    public javax.swing.JButton jButtonBusquedas;
    public javax.swing.JButton jButtonClientes;
    public javax.swing.JButton jButtonConsultorios;
    public javax.swing.JButton jButtonEmpleados;
    public javax.swing.JButton jButtonInstalaciones;
    public javax.swing.JButton jButtonSalir;
    public javax.swing.JButton jButtonSpace;
    public javax.swing.JButton jButtonTienda;
    public javax.swing.JButton jButtonTratamientos;
    public javax.swing.JButton jButtonTurnos;
    public javax.swing.JMenuBar jMenuBar;
    public javax.swing.JMenu jMenuBusquedas;
    public javax.swing.JMenu jMenuEmpleados;
    private javax.swing.JMenu jMenuEspaciador;
    public javax.swing.JMenuItem jMenuHistorialClientes;
    public javax.swing.JMenuItem jMenuHistorialProductos;
    public javax.swing.JMenuItem jMenuHistorialSes_Turnos;
    public javax.swing.JMenuItem jMenuHistorialTratamientos;
    public javax.swing.JMenuItem jMenuHistorialVentas;
    public javax.swing.JMenu jMenuTienda;
    public javax.swing.JMenuItem jMenuVerEmpleados;
    public javax.swing.JMenu jmSalir;
    // End of variables declaration//GEN-END:variables

    private void colocarIconos(){
        int alto = 50;
        int ancho = 50; 
        
        jButtonTurnos.setIcon(prepararIcono("iconTurnos.png",alto,ancho)); // asignamos al boton el icono
        jButtonBusquedas.setIcon(prepararIcono("icon_buscar.png",alto,ancho)); // asignamos al boton el icono
        jButtonClientes.setIcon(prepararIcono("iconClientes.png",alto,ancho)); // asignamos al boton el icono
        jButtonEmpleados.setIcon(prepararIcono("iconEmpleados.png",alto,ancho));
        jButtonInstalaciones.setIcon(prepararIcono("iconInstalaciones.png",alto,ancho));
        jButtonTratamientos.setIcon(prepararIcono("iconTratamientos.png",alto,ancho));
        jButtonConsultorios.setIcon(prepararIcono("iconConsultorios.png",alto,ancho));
        jButtonTienda.setIcon(prepararIcono("iconTienda.png",alto,ancho));
        jButtonSalir.setIcon(prepararIcono("icon_salir.png",alto,ancho));
        
        ImageIcon icono = new ImageIcon();
        icono = prepararIcono("IconVista.png",20,20);
        this.setIconImage(icono.getImage());
    }
    
    private ImageIcon prepararIcono(String nombre,int alto,int ancho){ // Aplicacion que prepara los Iconos para ser puestos donde se quiera se pasa el nombre y el tamaño que quieres que tenga
        // Obtén la ruta relativa a la ubicación de la clase Controlador eso es la carpeta SRC del proyecto ese seria la carpeta de inicio
        ClassLoader directorio = getClass().getClassLoader();
        URL imagen = directorio.getResource("Icons/" + nombre); // Creamos la ruta al recurso (iconos)
        // Crea un ImageIcon utilizando la URL de la imagen
        ImageIcon icono = new ImageIcon(imagen); // creamos la Imagen Icono para asignarsela al contenerdor
        // Redimensionar el icono pasandolo a imagen con el nuevo tamaño y luego convirtiendolo en icono XD
        Image imagenRedimensionada = icono.getImage().getScaledInstance(alto, ancho, Image.SCALE_SMOOTH);
        icono = new ImageIcon(imagenRedimensionada);
        return icono;
    }
}

