package Vistas;
/** 
    @author Grupo 6 
    Gimenez Diego Ruben
    Carlos German Mecias Giacomelli
    Tomas Migliozzi Badani
    Urbani Jose
**/
public class VistaProductos extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaProductos
     */
    public VistaProductos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlProductos = new javax.swing.JLabel();
        jlProductos1 = new javax.swing.JLabel();
        jtDescripcion = new javax.swing.JTextField();
        jlNroTratamiento = new javax.swing.JLabel();
        jlPrecio = new javax.swing.JLabel();
        jtStock = new javax.swing.JTextField();
        jlStock = new javax.swing.JLabel();
        jbtSalir = new javax.swing.JButton();
        jbtEliminar = new javax.swing.JButton();
        jbtGuardar = new javax.swing.JButton();
        jbtNuevo = new javax.swing.JButton();
        jlDescripcion = new javax.swing.JLabel();
        jtNroTratamiento = new javax.swing.JTextField();
        jbtVerificar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbProductos = new javax.swing.JTable();
        jtPrecio = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlProductos.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlProductos.setText("Productos");
        jPanel1.add(jlProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(632, 44, 70, 30));

        jlProductos1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jlProductos1.setForeground(new java.awt.Color(153, 0, 255));
        jlProductos1.setText("Gestor de Productos");
        jPanel1.add(jlProductos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 17, 327, 30));
        jPanel1.add(jtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 241, 218, 85));

        jlNroTratamiento.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jlNroTratamiento.setText("N° Tratamiento:");
        jPanel1.add(jlNroTratamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jlPrecio.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jlPrecio.setText("Precio:");
        jPanel1.add(jlPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));
        jPanel1.add(jtStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 190, 95, 27));

        jlStock.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jlStock.setText("Stock:");
        jPanel1.add(jlStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 193, -1, 18));

        jbtSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon_salir.png"))); // NOI18N
        jbtSalir.setText("Salir");
        jbtSalir.setMaximumSize(new java.awt.Dimension(125, 57));
        jbtSalir.setMinimumSize(new java.awt.Dimension(125, 57));
        jbtSalir.setPreferredSize(new java.awt.Dimension(125, 57));
        jPanel1.add(jbtSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(807, 338, -1, -1));

        jbtEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon_eliminar.png"))); // NOI18N
        jbtEliminar.setText("Eliminar");
        jbtEliminar.setMaximumSize(new java.awt.Dimension(125, 57));
        jbtEliminar.setMinimumSize(new java.awt.Dimension(125, 57));
        jbtEliminar.setPreferredSize(new java.awt.Dimension(125, 57));
        jPanel1.add(jbtEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, -1, -1));

        jbtGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon_guardar.png"))); // NOI18N
        jbtGuardar.setText("Guardar");
        jbtGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(jbtGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, -1, -1));

        jbtNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon_nuevo.png"))); // NOI18N
        jbtNuevo.setText("Nuevo");
        jbtNuevo.setMargin(new java.awt.Insets(3, 3, 3, 3));
        jbtNuevo.setMaximumSize(new java.awt.Dimension(125, 57));
        jbtNuevo.setMinimumSize(new java.awt.Dimension(125, 57));
        jbtNuevo.setPreferredSize(new java.awt.Dimension(125, 57));
        jPanel1.add(jbtNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 338, 110, -1));

        jlDescripcion.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jlDescripcion.setText("Descripcion:");
        jPanel1.add(jlDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 235, -1, -1));
        jPanel1.add(jtNroTratamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 95, 27));

        jbtVerificar.setBackground(new java.awt.Color(204, 204, 255));
        jbtVerificar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jbtVerificar.setForeground(new java.awt.Color(51, 0, 255));
        jbtVerificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon_buscar.png"))); // NOI18N
        jbtVerificar.setText("Verificar");
        jbtVerificar.setMargin(new java.awt.Insets(2, 6, 3, 6));
        jPanel1.add(jbtVerificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 80, -1, -1));

        jtbProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jtbProductos);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 80, 542, 248));
        jPanel1.add(jtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 95, 27));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 960, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JButton jbtEliminar;
    public javax.swing.JButton jbtGuardar;
    public javax.swing.JButton jbtNuevo;
    public javax.swing.JButton jbtSalir;
    public javax.swing.JButton jbtVerificar;
    private javax.swing.JLabel jlDescripcion;
    private javax.swing.JLabel jlNroTratamiento;
    private javax.swing.JLabel jlPrecio;
    private javax.swing.JLabel jlProductos;
    private javax.swing.JLabel jlProductos1;
    private javax.swing.JLabel jlStock;
    public javax.swing.JTextField jtDescripcion;
    public javax.swing.JTextField jtNroTratamiento;
    public javax.swing.JTextField jtPrecio;
    public javax.swing.JTextField jtStock;
    public javax.swing.JTable jtbProductos;
    // End of variables declaration//GEN-END:variables
}
