
package Vistas;

/** 
    @author Grupo 6 
    Gimenez Diego Ruben
    Carlos German Mecias Giacomelli
    Tomas Migliozzi Badani
    Urbani Jose
**/

public class VistaEmpleados extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaAlumnos
     */
    public VistaEmpleados() {
        initComponents();
        setTitle("Alumnos");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlAlumno = new javax.swing.JLabel();
        jlDocumento = new javax.swing.JLabel();
        jlApellido = new javax.swing.JLabel();
        jlNombre = new javax.swing.JLabel();
        jlTelefono = new javax.swing.JLabel();
        jbtNuevo = new javax.swing.JButton();
        jbtEliminar = new javax.swing.JButton();
        jbtGuardar = new javax.swing.JButton();
        jbtSalir = new javax.swing.JButton();
        jtxDocumento = new javax.swing.JTextField();
        jtxApellido = new javax.swing.JTextField();
        jtxNombre = new javax.swing.JTextField();
        jdcFechadeNacimiento = new com.toedter.calendar.JDateChooser();
        jbtBuscar = new javax.swing.JButton();
        jlEstado1 = new javax.swing.JLabel();
        jlFechaDeNacimiento1 = new javax.swing.JLabel();
        jComboBoxPuesto = new javax.swing.JComboBox<>();
        jlFechaDeNacimiento2 = new javax.swing.JLabel();
        jlMatricula = new javax.swing.JLabel();
        jtxTelefono = new javax.swing.JTextField();
        jlEspecialidad = new javax.swing.JLabel();
        jtxMatricula = new javax.swing.JTextField();
        jtxEspecialidad = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbEmpleados = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        cmbEspecialidadBuscar = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        jbtAltaBaja = new javax.swing.JButton();
        jCheckBoxEstado = new javax.swing.JCheckBox();
        rbtnActivo1 = new javax.swing.JRadioButton();
        rbtnInactivo1 = new javax.swing.JRadioButton();
        jbtModificar = new javax.swing.JButton();

        setResizable(false);
        setPreferredSize(new java.awt.Dimension(1120, 555));

        jlAlumno.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jlAlumno.setForeground(new java.awt.Color(0, 102, 255));
        jlAlumno.setText("Empleados");

        jlDocumento.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlDocumento.setText("D.N.I:");

        jlApellido.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jlApellido.setText("Apellido:");
        jlApellido.setToolTipText("");

        jlNombre.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jlNombre.setText("Nombre:");

        jlTelefono.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jlTelefono.setText("Teléfono:");
        jlTelefono.setToolTipText("");

        jbtNuevo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbtNuevo.setForeground(new java.awt.Color(51, 255, 0));
        jbtNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon_nuevo.png"))); // NOI18N
        jbtNuevo.setText("Nuevo");
        jbtNuevo.setIconTextGap(2);
        jbtNuevo.setMargin(new java.awt.Insets(2, 6, 2, 6));

        jbtEliminar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jbtEliminar.setForeground(new java.awt.Color(255, 0, 51));
        jbtEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon_eliminar.png"))); // NOI18N
        jbtEliminar.setText("Eliminar");
        jbtEliminar.setAlignmentY(0.0F);
        jbtEliminar.setIconTextGap(2);
        jbtEliminar.setMargin(new java.awt.Insets(6, 6, 6, 6));

        jbtGuardar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbtGuardar.setForeground(new java.awt.Color(0, 204, 102));
        jbtGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon_guardar.png"))); // NOI18N
        jbtGuardar.setText("Guardar");
        jbtGuardar.setIconTextGap(2);
        jbtGuardar.setMargin(new java.awt.Insets(2, 6, 2, 6));

        jbtSalir.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jbtSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon_salir.png"))); // NOI18N
        jbtSalir.setText("Salir");
        jbtSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSalirActionPerformed(evt);
            }
        });

        jtxDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxDocumentoActionPerformed(evt);
            }
        });

        jbtBuscar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jbtBuscar.setForeground(new java.awt.Color(51, 0, 255));
        jbtBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon_buscar.png"))); // NOI18N
        jbtBuscar.setText("Buscar");
        jbtBuscar.setMargin(new java.awt.Insets(2, 6, 3, 6));
        jbtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtBuscarActionPerformed(evt);
            }
        });

        jlEstado1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jlEstado1.setText("Estado");

        jlFechaDeNacimiento1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jlFechaDeNacimiento1.setText("Fecha Nac.:");
        jlFechaDeNacimiento1.setToolTipText("");

        jComboBoxPuesto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxPuesto.setMinimumSize(null);

        jlFechaDeNacimiento2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jlFechaDeNacimiento2.setText("Puesto:");
        jlFechaDeNacimiento2.setToolTipText("");

        jlMatricula.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jlMatricula.setText("Matrícula:");
        jlMatricula.setToolTipText("");

        jlEspecialidad.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jlEspecialidad.setText("Especialidad:");
        jlEspecialidad.setToolTipText("");

        jtxMatricula.setMinimumSize(null);
        jtxMatricula.setPreferredSize(null);

        jtxEspecialidad.setMinimumSize(null);

        tbEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbEmpleados.setMaximumSize(new java.awt.Dimension(2147483647, 900));
        tbEmpleados.setPreferredSize(new java.awt.Dimension(300, 90));
        jScrollPane1.setViewportView(tbEmpleados);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Especialidad");

        cmbEspecialidadBuscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbEspecialidadBuscar.setSelectedIndex(-1);
        cmbEspecialidadBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEspecialidadBuscarActionPerformed(evt);
            }
        });

        jLabel8.setText("Matricula");

        jbtAltaBaja.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jbtAltaBaja.setForeground(new java.awt.Color(204, 0, 204));
        jbtAltaBaja.setText("Dar: Alta - Baja");
        jbtAltaBaja.setIconTextGap(2);
        jbtAltaBaja.setMargin(new java.awt.Insets(2, 6, 2, 6));

        rbtnActivo1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        rbtnActivo1.setForeground(new java.awt.Color(0, 204, 0));
        rbtnActivo1.setSelected(true);
        rbtnActivo1.setText("Activos");

        rbtnInactivo1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        rbtnInactivo1.setForeground(new java.awt.Color(255, 51, 51));
        rbtnInactivo1.setText("Inactivos");

        jbtModificar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbtModificar.setForeground(new java.awt.Color(255, 204, 0));
        jbtModificar.setText("Modificar");
        jbtModificar.setIconTextGap(2);
        jbtModificar.setMargin(new java.awt.Insets(2, 6, 2, 6));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlFechaDeNacimiento1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jdcFechadeNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jlEstado1)
                                .addGap(6, 6, 6))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jlDocumento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbtBuscar))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jlApellido)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtxApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlNombre)
                                .addGap(12, 12, 12)
                                .addComponent(jtxNombre))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(jlFechaDeNacimiento2))
                                    .addComponent(jlEspecialidad)
                                    .addComponent(jlMatricula, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jtxMatricula, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtxEspecialidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBoxPuesto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jlTelefono)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jCheckBoxEstado)
                                .addGap(22, 22, 22))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jbtNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbtGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbtModificar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jbtEliminar)
                                        .addGap(1, 1, 1))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlAlumno)
                        .addGap(50, 50, 50)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbEspecialidadBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(27, 27, 27)
                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(rbtnActivo1)
                        .addGap(18, 18, 18)
                        .addComponent(rbtnInactivo1)
                        .addGap(18, 18, 18)
                        .addComponent(jbtAltaBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addComponent(jbtSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cmbEspecialidadBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jlAlumno)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(5, 5, 5))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jbtSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rbtnInactivo1)
                                    .addComponent(rbtnActivo1)
                                    .addComponent(jbtAltaBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtBuscar)
                            .addComponent(jlDocumento))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlApellido)
                            .addComponent(jtxApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlNombre)
                            .addComponent(jtxNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlFechaDeNacimiento1)
                            .addComponent(jdcFechadeNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlEstado1))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jlTelefono)
                                .addComponent(jtxTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jCheckBoxEstado))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlFechaDeNacimiento2))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlMatricula)
                            .addComponent(jtxMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlEspecialidad)
                            .addComponent(jtxEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1))
                            .addComponent(jbtGuardar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtSalirActionPerformed

    private void jtxDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxDocumentoActionPerformed

    private void jbtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtBuscarActionPerformed

    private void cmbEspecialidadBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEspecialidadBuscarActionPerformed
        String especialidad = (String) cmbEspecialidadBuscar.getSelectedItem();

        /*listarPorEspecialidad(especialidad);*/
    }//GEN-LAST:event_cmbEspecialidadBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbEspecialidadBuscar;
    public javax.swing.JCheckBox jCheckBoxEstado;
    public javax.swing.JComboBox<String> jComboBoxPuesto;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton jbtAltaBaja;
    public javax.swing.JButton jbtBuscar;
    public javax.swing.JButton jbtEliminar;
    public javax.swing.JButton jbtGuardar;
    public javax.swing.JButton jbtModificar;
    public javax.swing.JButton jbtNuevo;
    public javax.swing.JButton jbtSalir;
    public com.toedter.calendar.JDateChooser jdcFechadeNacimiento;
    private javax.swing.JLabel jlAlumno;
    private javax.swing.JLabel jlApellido;
    private javax.swing.JLabel jlDocumento;
    private javax.swing.JLabel jlEspecialidad;
    private javax.swing.JLabel jlEstado1;
    private javax.swing.JLabel jlFechaDeNacimiento1;
    private javax.swing.JLabel jlFechaDeNacimiento2;
    private javax.swing.JLabel jlMatricula;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JLabel jlTelefono;
    public javax.swing.JTextField jtxApellido;
    public javax.swing.JTextField jtxDocumento;
    public javax.swing.JTextField jtxEspecialidad;
    public javax.swing.JTextField jtxMatricula;
    public javax.swing.JTextField jtxNombre;
    public javax.swing.JTextField jtxTelefono;
    private javax.swing.JRadioButton rbtnActivo1;
    private javax.swing.JRadioButton rbtnInactivo1;
    public javax.swing.JTable tbEmpleados;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
