package Vistas;

/*  @author Grupo 6 
    Gimenez Diego Ruben
    Carlos German Mecias Giacomelli
    Tomas Migliozzi Badani
    Urbani Jose
 */
public class VistaDiaDeSpa extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaDiaDeSpa
     */
    public VistaDiaDeSpa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jPanelFondoDiaSpa = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jdcListarFecha = new com.toedter.calendar.JDateChooser();
        rbtnActivo = new javax.swing.JRadioButton();
        rbtnInactivo = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbSesiones = new javax.swing.JTable();
        btnAgregarSesiones = new javax.swing.JButton();
        jbtSalir = new javax.swing.JButton();
        rbtnTodos = new javax.swing.JRadioButton();
        jbtNuevo = new javax.swing.JButton();
        jbtEliminar = new javax.swing.JButton();
        jbtBuscar = new javax.swing.JButton();
        jcheckbEstado = new javax.swing.JCheckBox();
        jLabelTituloDiaDeSpa = new javax.swing.JLabel();
        jlDNI = new javax.swing.JLabel();
        jtxDNI = new javax.swing.JTextField();
        jlNombre = new javax.swing.JLabel();
        jtxNombre = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaPreferencias = new javax.swing.JTextArea();
        jtxTelefono = new javax.swing.JTextField();
        jlPreferencias = new javax.swing.JLabel();
        jcboxHora = new javax.swing.JComboBox<>();
        jlHora = new javax.swing.JLabel();
        jdcFecha = new com.toedter.calendar.JDateChooser();
        jlFecha = new javax.swing.JLabel();
        jlTelefono = new javax.swing.JLabel();
        jbtGuardar = new javax.swing.JButton();
        jlNombre1 = new javax.swing.JLabel();

        jFormattedTextField1.setText("jFormattedTextField1");

        setBackground(new java.awt.Color(255, 255, 255));

        jPanelFondoDiaSpa.setBackground(new java.awt.Color(255, 204, 204));
        jPanelFondoDiaSpa.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Listar por fecha:");
        jPanelFondoDiaSpa.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, -1, -1));
        jPanelFondoDiaSpa.add(jdcListarFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 101, -1));

        rbtnActivo.setBackground(new java.awt.Color(255, 204, 204));
        rbtnActivo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        rbtnActivo.setForeground(new java.awt.Color(51, 255, 51));
        rbtnActivo.setText("Activos");
        jPanelFondoDiaSpa.add(rbtnActivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 50, -1, -1));

        rbtnInactivo.setBackground(new java.awt.Color(255, 204, 204));
        rbtnInactivo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        rbtnInactivo.setForeground(new java.awt.Color(255, 0, 0));
        rbtnInactivo.setText("Inactivos");
        jPanelFondoDiaSpa.add(rbtnInactivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 50, -1, -1));

        tbSesiones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbSesiones);

        jPanelFondoDiaSpa.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 81, 610, 380));

        btnAgregarSesiones.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnAgregarSesiones.setForeground(new java.awt.Color(51, 0, 255));
        btnAgregarSesiones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon_inscribir.png"))); // NOI18N
        btnAgregarSesiones.setText("Agregar Sesiones");
        btnAgregarSesiones.setMargin(new java.awt.Insets(2, 5, 3, 5));
        jPanelFondoDiaSpa.add(btnAgregarSesiones, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 470, -1, -1));

        jbtSalir.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jbtSalir.setForeground(new java.awt.Color(255, 0, 51));
        jbtSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon_salir.png"))); // NOI18N
        jbtSalir.setText("Salir");
        jbtSalir.setMaximumSize(new java.awt.Dimension(125, 57));
        jbtSalir.setMinimumSize(new java.awt.Dimension(125, 57));
        jbtSalir.setPreferredSize(new java.awt.Dimension(125, 57));
        jPanelFondoDiaSpa.add(jbtSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 470, -1, -1));

        rbtnTodos.setBackground(new java.awt.Color(255, 204, 204));
        rbtnTodos.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        rbtnTodos.setForeground(new java.awt.Color(255, 255, 255));
        rbtnTodos.setSelected(true);
        rbtnTodos.setText("Todos los clientes");
        rbtnTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnTodosActionPerformed(evt);
            }
        });
        jPanelFondoDiaSpa.add(rbtnTodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 50, -1, -1));

        jbtNuevo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jbtNuevo.setForeground(new java.awt.Color(0, 204, 102));
        jbtNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon_agregar.png"))); // NOI18N
        jbtNuevo.setText("Nuevo");
        jbtNuevo.setMargin(new java.awt.Insets(2, 3, 3, 3));
        jbtNuevo.setMaximumSize(new java.awt.Dimension(125, 57));
        jbtNuevo.setMinimumSize(new java.awt.Dimension(125, 57));
        jbtNuevo.setPreferredSize(new java.awt.Dimension(125, 57));
        jPanelFondoDiaSpa.add(jbtNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, 55));

        jbtEliminar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jbtEliminar.setForeground(new java.awt.Color(255, 0, 51));
        jbtEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon_eliminar.png"))); // NOI18N
        jbtEliminar.setText("Eliminar");
        jbtEliminar.setMargin(new java.awt.Insets(2, 5, 3, 5));
        jbtEliminar.setMaximumSize(new java.awt.Dimension(125, 57));
        jbtEliminar.setMinimumSize(new java.awt.Dimension(125, 57));
        jbtEliminar.setPreferredSize(new java.awt.Dimension(125, 57));
        jPanelFondoDiaSpa.add(jbtEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 470, 112, -1));

        jbtBuscar.setBackground(new java.awt.Color(204, 204, 255));
        jbtBuscar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jbtBuscar.setForeground(new java.awt.Color(51, 0, 255));
        jbtBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon_buscar.png"))); // NOI18N
        jbtBuscar.setText("Buscar");
        jbtBuscar.setMargin(new java.awt.Insets(2, 6, 3, 6));
        jbtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtBuscarActionPerformed(evt);
            }
        });
        jPanelFondoDiaSpa.add(jbtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 81, 100, 50));

        jcheckbEstado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jcheckbEstado.setText("(activo/inactivo)");
        jPanelFondoDiaSpa.add(jcheckbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        jLabelTituloDiaDeSpa.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabelTituloDiaDeSpa.setForeground(new java.awt.Color(255, 102, 102));
        jLabelTituloDiaDeSpa.setText("Dia de Spa (TURNO)");
        jPanelFondoDiaSpa.add(jLabelTituloDiaDeSpa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 30));

        jlDNI.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlDNI.setText("DNI:");
        jPanelFondoDiaSpa.add(jlDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));
        jPanelFondoDiaSpa.add(jtxDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 90, -1));

        jlNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlNombre.setText("Estado:");
        jPanelFondoDiaSpa.add(jlNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));
        jPanelFondoDiaSpa.add(jtxNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 220, -1));

        jTextAreaPreferencias.setColumns(20);
        jTextAreaPreferencias.setRows(5);
        jScrollPane2.setViewportView(jTextAreaPreferencias);

        jPanelFondoDiaSpa.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 307, 81));
        jPanelFondoDiaSpa.add(jtxTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 113, -1));

        jlPreferencias.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlPreferencias.setText("Preferencias:");
        jPanelFondoDiaSpa.add(jlPreferencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        jcboxHora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanelFondoDiaSpa.add(jcboxHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, -1, -1));

        jlHora.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlHora.setText("Hora:");
        jPanelFondoDiaSpa.add(jlHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, -1, -1));
        jPanelFondoDiaSpa.add(jdcFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 101, -1));

        jlFecha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlFecha.setText("Fecha:");
        jPanelFondoDiaSpa.add(jlFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        jlTelefono.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlTelefono.setText("Teléfono:");
        jPanelFondoDiaSpa.add(jlTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jbtGuardar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jbtGuardar.setForeground(new java.awt.Color(0, 204, 102));
        jbtGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon_guardar.png"))); // NOI18N
        jbtGuardar.setText("Guardar");
        jPanelFondoDiaSpa.add(jbtGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, -1, -1));

        jlNombre1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlNombre1.setText("Nombre:");
        jPanelFondoDiaSpa.add(jlNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondoDiaSpa, javax.swing.GroupLayout.DEFAULT_SIZE, 985, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelFondoDiaSpa, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtBuscarActionPerformed

    private void rbtnTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnTodosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnTodosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAgregarSesiones;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelTituloDiaDeSpa;
    public javax.swing.JPanel jPanelFondoDiaSpa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTextArea jTextAreaPreferencias;
    public javax.swing.JButton jbtBuscar;
    public javax.swing.JButton jbtEliminar;
    public javax.swing.JButton jbtGuardar;
    public javax.swing.JButton jbtNuevo;
    public javax.swing.JButton jbtSalir;
    public javax.swing.JComboBox<String> jcboxHora;
    public javax.swing.JCheckBox jcheckbEstado;
    public com.toedter.calendar.JDateChooser jdcFecha;
    public com.toedter.calendar.JDateChooser jdcListarFecha;
    private javax.swing.JLabel jlDNI;
    private javax.swing.JLabel jlFecha;
    private javax.swing.JLabel jlHora;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JLabel jlNombre1;
    private javax.swing.JLabel jlPreferencias;
    private javax.swing.JLabel jlTelefono;
    public javax.swing.JTextField jtxDNI;
    public javax.swing.JTextField jtxNombre;
    public javax.swing.JTextField jtxTelefono;
    public javax.swing.JRadioButton rbtnActivo;
    public javax.swing.JRadioButton rbtnInactivo;
    public javax.swing.JRadioButton rbtnTodos;
    public javax.swing.JTable tbSesiones;
    // End of variables declaration//GEN-END:variables
}
