/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

/**
 *
 * @author urban
 */
public class VistaBusquedaDiaDeSpa extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaBusquedaDiaDeSpa
     */
    public VistaBusquedaDiaDeSpa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTituloDiaDeSpa = new javax.swing.JLabel();
        rbtnActivo1 = new javax.swing.JRadioButton();
        rbtnInactivo1 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbTurnos = new javax.swing.JTable();
        jbtSeleccionar = new javax.swing.JButton();
        jbtSalir = new javax.swing.JButton();
        rbtnTodos = new javax.swing.JRadioButton();

        jLabelTituloDiaDeSpa.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelTituloDiaDeSpa.setText("Turnos");

        rbtnActivo1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        rbtnActivo1.setForeground(new java.awt.Color(0, 204, 0));
        rbtnActivo1.setText("Activos");

        rbtnInactivo1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        rbtnInactivo1.setForeground(new java.awt.Color(255, 51, 51));
        rbtnInactivo1.setText("Inactivos");

        tbTurnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbTurnos.setMaximumSize(new java.awt.Dimension(2147483647, 900));
        tbTurnos.setPreferredSize(null);
        jScrollPane1.setViewportView(tbTurnos);

        jbtSeleccionar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jbtSeleccionar.setForeground(new java.awt.Color(51, 255, 0));
        jbtSeleccionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon_nuevo.png"))); // NOI18N
        jbtSeleccionar.setText("Seleccionar");
        jbtSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSeleccionarActionPerformed(evt);
            }
        });

        jbtSalir.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jbtSalir.setForeground(new java.awt.Color(255, 0, 51));
        jbtSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon_salir.png"))); // NOI18N
        jbtSalir.setText("Salir");
        jbtSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSalirActionPerformed(evt);
            }
        });

        rbtnTodos.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        rbtnTodos.setSelected(true);
        rbtnTodos.setText("Todos");
        rbtnTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnTodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(rbtnTodos)
                        .addGap(142, 142, 142)
                        .addComponent(rbtnActivo1)
                        .addGap(31, 31, 31)
                        .addComponent(rbtnInactivo1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtSeleccionar)
                            .addComponent(jLabelTituloDiaDeSpa, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbtnTodos)
                            .addComponent(rbtnActivo1)
                            .addComponent(rbtnInactivo1))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabelTituloDiaDeSpa, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(148, 148, 148)
                        .addComponent(jbtSeleccionar)
                        .addGap(175, 175, 175)
                        .addComponent(jbtSalir)))
                .addGap(0, 30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSeleccionarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtSeleccionarActionPerformed

    private void jbtSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtSalirActionPerformed

    private void rbtnTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnTodosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnTodosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelTituloDiaDeSpa;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton jbtSalir;
    public javax.swing.JButton jbtSeleccionar;
    public javax.swing.JRadioButton rbtnActivo1;
    public javax.swing.JRadioButton rbtnInactivo1;
    public javax.swing.JRadioButton rbtnTodos;
    public javax.swing.JTable tbTurnos;
    // End of variables declaration//GEN-END:variables
}
